db:
  host: "localhost"
  port: 3306
  username: "user"
  password: "password"

universe-land:
  land-price: 5
  deny-worlds:
    - hoge

mywarp:
  settings:
    deny-worlds: [ ]

customname:
  "yurisi": "yurisi"