db:
  host: "db"
  port: 3306
  username: "root"
  password: "password"

universe-land:
  land-price: 5
  deny-worlds:
    - hoge

mywarp:
  settings:
    deny-worlds: [ ]

tpp:
  settings:
    deny-worlds: [ ]

customname:
  "yurisi": "yurisi"
