name: UniverseCoreV2
version: '1.0'
main: space.yurisi.universecorev2.UniverseCoreV2
api-version: '1.21'
depend:
  - LuckPerms
commands:
  # UniverseCoreV2
  menu:
    description: メインメニューを開きます
    aliases: [ m ]
  password:
    description: UniverseCoreV2 のパスワードを設定します
  pplayer:
    description: あなたの役職を確認します
  giveu:
    description: オンラインのプレイヤーに経験値を与えます
  flat:
    description: フラットワールドに行きます。

  # SubPlugins

  ## LevelSystem
  addexp:
    description: 指定したプレイヤーに経験値を追加します

  ## UniverseEconomy
  money:
    description: お金管理のメニューを表示します (未実装)
  mymoney:
    description: 自分の持っているお金を確認します
  pay:
    description: 指定したプレイヤーにお金を払います
  seemoney:
    description: 他のプレイヤーのお金を確認します
  setmoney:
    description: 他のプレイヤーのお金をセットします
  addmoney:
    description: 他のプレイヤーのお金を増やします
  reducemoney:
    description: 他のプレイヤーのお金を減らします

  ## UniverseLand
  land:
    description: 土地を管理します

  ## Mywarp
  mywarp:
    description: マイワープの作成、管理を行います
    aliases: [mw]

  ## TPP
  tpp:
    description: プレイヤー間移動を行います

  ## Suicide
  su:
    description: 自滅します

  ## UniverseUtils
  trash:
    description: アイテムを捨てることができるゴミ箱を開きます
    aliases: [ gomi ]
  dice:
    description: サイコロを振ります
  k:
    description: こんにちはの顔文字を送信します
  oti:
    description: おちるときのの顔文字を送信します
  otu:
    description: おつかれの顔文字を送信します

  ## XTP
  xtp:
    description: 指定したワールド、座標にテレポートします

  ## Navigation
  wiki:
    description: Wiki へのURLを表示します
  discord:
    description: Discord の招待URLを表示します
  web:
    description: UniverseWeb へのURLを表示します

  ## ItemHat
  hat:
    description: 手に持っているアイテムを頭にかぶります

  ## CustomName
  tag:
    description: 称号を設定します

  ## ContainerProtect
  lock:
    description: コンテナ等を保護します
  unlock:
    description: コンテナ等の保護を解除します

  ## UniverseGuns
  ammo:
    description: 弾薬管理メニューを開く
  spawnGunClerk:
    description: 銃ショップの店員召喚
  killGunClerk:
    description: 半径5ブロック以内の指定したショップの店員を排除します

  ## PlayerHead
  head:
    description: プレイヤーヘッドを購入します(WIP)

  ## Gacha
  gacha:
    description: ガチャを引きます！

  ## FreeMarket
  market:
    description: フリーマーケットの画面を開きます

  ## RepairCream
  repair:
    description: アイテムを修復します

  ## ChestShop
  item:
    description: メインハンドに持ったアイテムの名前を表示します

  ## AutoCollect
  autocollect:
    description: 自動収集機能のオンオフを切り替えます
    aliases: [ ac ]

  # ReceiveBox
  receive:
    description: アイテム受取ボックスを表示します
  addreceive:
    description: アイテム受取ボックスに追加します

  # BirthdayCard
  birthday:
    description: お誕生日カードメニューを開きます

  # Achievement
  achievement:
    description: 実績メニューを開きます

  #loginbonus
  loginbonus:
    description: ログインボーナスを開きます

  #levelreward
  reward:
    description: レベル報酬を受け取る

  #job
  job:
    description: 仕事メニューを開きます

  #slot
  slot:
    description: スロットマシンを設定します

  #PositionSystem
  gm:
    description: ゲームモードを切り替えます

  #cooking:
  cooking:
    description: レシピを編集します

  #fly
  fly:
    description: 飛行モードを切り替えます
