name: UniverseCoreV2
version: '1.0'
main: space.yurisi.universecorev2.UniverseCoreV2
api-version: '1.21'
commands:
  password:
    description: パスワードを設定します
  pplayer:
    description: あなたの役職を確認します
  giveu:
    description: オンラインのプレイヤーに経験値を与えます
    permission: space.yurisi.universecorev2.giveu

  #SubPlugins
  #LevelSystem
  addexp:
        description: オンラインのプレイヤーに経験値を与えます
        permission: space.yurisi.levelsystem.addexp

  #UniverseEconomy
  money:
    description: お金管理のメニューを表示します
    permission: space.yurisi.universeeconomy.money
  mymoney:
    description: 自分の持っているお金を確認します。
    permission: space.yurisi.universeeconomy.mymoney
  pay:
    description: プレイヤーにお金を払います。
    permission: space.yurisi.universeeconomy.pay
  seemoney:
    description: 他のプレイヤーのお金を確認します
    permission: space.yurisi.universeeconomy.seemoney
  setmoney:
    description: 他のプレイヤーのお金をセットします
    permission: space.yurisi.universeeconomy.setmoney
  addmoney:
    description: 他のプレイヤーのお金を増やします
    permission: space.yurisi.universeeconomy.addmoney
  reducemoney:
    description: 他のプレイヤーのお金を減らします
    permission: space.yurisi.universeeconomy.reducemoney

  #UniverseLand
  land:
    description: 土地を管理します

  #UniverseDice
  dice:
    description: サイコロを振ります

  #Mywarp
  mywarp:
    description: マイワープを作成、ワープできます
    aliases: [mw]

  #TPP
  tpp:
      description: プレイヤーをテレポートします
      usage: /tpp

  #Salute
  k:
    description: こんにちはの顔文字を送信します
  oti:
    description: おちるときのの顔文字を送信します
  otu:
    description: おつかれの顔文字を送信します

  #Suicide
  su:
    description: 自殺します

  xtp:
    description: テレポートします

  lobby:
    description: ロビーに戻ります

  #ItemHat
  hat:
    discription: 手に持っているアイテムを頭にかぶります

  #CustomName
  tag:
    description: 称号を設定します

  #ContainerProtect
  lock:
    description: コンテナ等を保護します
  unlock:
    description: コンテナ等の保護を解除します

  #gacha
  gacha:
    description: ガチャを引きます！

  #FreeMarket
  market:
    description: フリーマーケットの画面を開きます
    usage: /market

  #RepairCream
  repair:
    description: アイテムを修復します

permissions:
  # UniverseCoreV2
  space.yurisi.universecorev2.interactevent.enchanttable:
    default: op
  space.yurisi.universecorev2.giveu:
    description: op command
    default: op

  #SubPlugins
  #LevelSystem
  space.yurisi.levelsystem.addexp:
    description: op command
    default: op

  #UniverseEconomy
  space.yurisi.universeeconomy.*:
    description: default
    default: true
    children:
      space.yurisi.universeeconomy.money: true
      space.yurisi.universeeconomy.mymoney: true
      space.yurisi.universeeconomy.pay: true
      space.yurisi.universeeconomy.seemoney: true
  space.yurisi.universeeconomy.setmoney:
    description: op command
    default: op
  space.yurisi.universeeconomy.addmoney:
    description: op command
    default: op
  space.yurisi.universeeconomy.reducemoney:
    description: op command
    default: op

