use SpaceServerUniverse;

CREATE TABLE IF NOT EXISTS counts(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL UNIQUE,
    CONSTRAINT FK_USERS_COUNTS_USER_ID FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS kill_death_counts(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    count_id BIGINT UNSIGNED NOT NULL UNIQUE,
    player_kill BIGINT UNSIGNED NOT NULL DEFAULT 0,
    mob_kill BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ender_dragon_kill BIGINT NOT NULL DEFAULT 0,
    wither_kill BIGINT NOT NULL DEFAULT 0,
    death BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT FK_COUNTERS_KILL_DEATH_COUNTS_COUNTER_ID FOREIGN KEY (count_id) REFERENCES counts (id)
);

CREATE TABLE IF NOT EXISTS ore_counts(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    count_id BIGINT UNSIGNED NOT NULL UNIQUE,
    coal_ore BIGINT UNSIGNED NOT NULL DEFAULT 0,
    iron_ore BIGINT UNSIGNED NOT NULL DEFAULT 0,
    gold_ore BIGINT UNSIGNED NOT NULL DEFAULT 0,
    lapis_ore BIGINT UNSIGNED NOT NULL DEFAULT 0,
    redstone_ore BIGINT UNSIGNED NOT NULL DEFAULT 0,
    emerald_ore BIGINT UNSIGNED NOT NULL DEFAULT 0,
    diamond_ore BIGINT UNSIGNED NOT NULL DEFAULT 0,
    copper_ore BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT FK_COUNTERS_ORE_COUNTS_COUNTER_ID FOREIGN KEY (count_id) REFERENCES counts (id)
);

CREATE TABLE IF NOT EXISTS life_counts(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    count_id BIGINT UNSIGNED NOT NULL UNIQUE,
    fishing BIGINT UNSIGNED NOT NULL DEFAULT 0,
    block_break BIGINT UNSIGNED NOT NULL DEFAULT 0,
    block_place BIGINT UNSIGNED NOT NULL DEFAULT 0,
    flower_place BIGINT UNSIGNED NOT NULL DEFAULT 0,
    wood_break BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT FK_COUNTERS_LIFE_COUNTS_COUNTER_ID FOREIGN KEY (count_id) REFERENCES counts (id)
);

CREATE TABLE IF NOT EXISTS player_counts(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    count_id BIGINT UNSIGNED NOT NULL UNIQUE,
    login BIGINT UNSIGNED NOT NULL DEFAULT 0,
    consecutive_login BIGINT UNSIGNED NOT NULL DEFAULT 0,
    last_login_date DATE NOT NULL,
    CONSTRAINT FK_COUNTERS_PLAYER_COUNTS_COUNTER_ID FOREIGN KEY (count_id) REFERENCES counts (id)
);