use SpaceServerUniverse;

CREATE TABLE IF NOT EXISTS tile_protects (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(255) NOT NULL,
    x BIGINT NOT NULL,
    y BIGINT NOT NULL,
    z BIGINT NOT NULL,
    world_name VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
