use SpaceServerUniverse;

CREATE TABLE IF NOT EXISTS autotppsetting(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    is_auto_accept BOOLEAN NOT NULL DEFAULT FALSE
);